name: Workflow to run sequential & parallel jobs

on: 
  workflow_dispatch:

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: "Running ${{ github.job }}"
        run: echo "${{ github.job }} is running..."

  job_2:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: "Running ${{ github.job }}"
        run: echo "${{ github.job }} is running..."

  job_3:
    runs-on: ubuntu-latest
    needs: job_1
    steps:
      - name: "Running ${{ github.job }}"
        run: echo "${{ github.job }} is running..."

  job_4:
    runs-on: ubuntu-latest
    needs: [job_2, job_3]
    steps:
      - name: "Running ${{ github.job }}"
        run: echo "${{ github.job }} is running..."
