name: Workflow for test program in different os

on: 
  workflow_dispatch:

jobs:
  job-1:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latet, windows-latest, macos-latest]
        node_version: [14.x, 15.x, 16.x]
    runs-on: $${{ matrix.os }}
    steps:
      - name: Setup Node Environment
        uses: actions/setup-node@v6.4.0
        with:
          node-version: $$ {{ matrix.node_version }}

      - name: Output the node version
        run: node --version
